future: false
safe: false
timezone: "Europe/Madrid"
exclude: [README.md, Rakefile, Gemfile, Gemfile.lock, guayaba.todo, config.rb, bootstrap-sass.gemspec]
paginate: 10
excerpt_separator: "</sep>"

collections:
    plataformas:
        output: true
    colecciones:
        output: true
        layout: coleccion